### ISSUE TITLE
Add image/gif validation support for ProductOptionValueImage

### ISSUE THREAD

**Issue by Loocos** [monsieurbiz/SyliusAdvancedOptionPlugin#4]
Hi,

Is it possible to add the support of gif image to the ProductOptionValueImage entity please ?

` 
                      - "image/gif"
`

Thanks in advance :D

**Comment by Loocos** [comment]
Hello @jacquesbh,

Thanks to did it as fast as possible, but when will it be merged please ?

**Comment by maximehuran** [comment]
Hi, we will first make the CI run correctly.
I made the PR #6 for that.
When we will merge it, we will rebase the #5 and check everything is OK before merge.

**Comment by maximehuran** [comment]
@Loocos the new tag v1.0.0-RC.2 is available
